/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DatePicker: typeof import('./src/components/global/datePicker/index.vue')['default']
    Pagination: typeof import('./src/components/global/pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/global/svgIcon/index.vue')['default']
    TreeSelect: typeof import('./src/components/global/treeSelect/index.vue')['default']
    Upload: typeof import('./src/components/global/upload/index.vue')['default']
    UploadList: typeof import('./src/components/global/uploadList/index.vue')['default']
  }
}
